# Generated by Django 5.2.7 on 2025-10-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0004_remove_skill_user'),
        ('users', '0006_alter_customuser_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skill',
            field=models.ManyToManyField(blank=True, to='job_application.skill'),
        ),
    ]
