# Generated by Django 5.2.7 on 2025-10-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='application',
            table='applications',
        ),
        migrations.AlterModelTable(
            name='job',
            table='jobs',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='skills',
        ),
    ]
