# Generated by Django 5.2.7 on 2025-10-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_alter_application_table_alter_job_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='skill',
            field=models.ManyToManyField(to='job_application.skill'),
        ),
    ]
