# Generated by Django 5.2.7 on 2025-10-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0003_remove_skill_job_job_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
    ]
